require_relative "./beer_presenter/version"
require_relative "./beer_presenter/cli"
require_relative "./beer_presenter/beer"
require_relative "./beer_presenter/brewery"
require_relative "./beer_presenter/style"
require_relative "./beer_presenter/scraper"
